
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.appmovil.analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int GUION = 11;
  public static final int CADENA = 12;
  public static final int GUION_BAJO = 10;
  public static final int DECIMAL = 2;
  public static final int CORCHETE_CERRADO = 7;
  public static final int DOS_PUNTOS = 8;
  public static final int LLAVE_ABIERTA = 4;
  public static final int COMA = 9;
  public static final int NUEVO = 17;
  public static final int NOMBRE = 15;
  public static final int EOF = 0;
  public static final int CREACION = 19;
  public static final int INSTITUCION = 16;
  public static final int FECHA = 18;
  public static final int PASSWORD = 14;
  public static final int error = 1;
  public static final int USUARIO = 13;
  public static final int ENTERO = 3;
  public static final int LLAVE_CERRADA = 5;
  public static final int CORCHETE_ABIERTO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECIMAL",
  "ENTERO",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "DOS_PUNTOS",
  "COMA",
  "GUION_BAJO",
  "GUION",
  "CADENA",
  "USUARIO",
  "PASSWORD",
  "NOMBRE",
  "INSTITUCION",
  "NUEVO",
  "FECHA",
  "CREACION"
  };
}

